//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int id { get; set; }
        public int client { get; set; }
        public int employee { get; set; }
        public int service { get; set; }
        public int status { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual AppointmentStatus AppointmentStatus { get; set; }
        public virtual Client Client1 { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Service Service1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
