//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int id { get; set; }
        public int appointment { get; set; }
        public int method { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Appointment Appointment1 { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
